# Generated by Django 3.1.6 on 2021-02-09 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MyStockHistorical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateField(verbose_name='Date')),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('vol', models.FloatField(verbose_name='Volume (000)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.mystock')),
            ],
            options={
                'unique_together': {('stock', 'on')},
                'index_together': {('stock', 'on')},
            },
        ),
        migrations.CreateModel(
            name='MyStrategyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(choices=[(1, 'daily return'), (2, 'overnight return')], default=1)),
                ('val', models.FloatField(blank=True, default=-1, null=True)),
                ('hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.mystockhistorical')),
            ],
        ),
        migrations.CreateModel(
            name='MySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('code', models.CharField(max_length=8, verbose_name='Sector code')),
                ('description', models.TextField(blank=True, null=True)),
                ('stocks', models.ManyToManyField(to='stock.MyStock')),
            ],
        ),
    ]
