# Generated by Django 3.1.6 on 2021-02-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210210_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystrategyvalue',
            name='method',
            field=models.IntegerField(choices=[(1, 'daily return'), (2, 'overnight return'), (3, 'night day consistency'), (4, 'trend')], default=1),
        ),
    ]
