# Generated by Django 3.1.6 on 2021-02-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_incomestatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatement',
            name='ebit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='general_and_administrative_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='gross_profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='net_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='normalized_ebitda',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='normalized_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operating_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operating_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operating_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='pretax_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='reconciled_cost_of_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='research_and_development',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='selling_and_marketing_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='selling_general_and_administration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='total_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='total_operating_income_as_reported',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='total_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
