# Generated by Django 3.1.6 on 2021-02-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210213_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='net_income_over_total_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='operating_revenue_over_total_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
