# Generated by Django 3.1.6 on 2021-02-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210213_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomestatement',
            old_name='net_income_over_total_revenue',
            new_name='gross_profit_margin',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='operating_revenue_over_total_revenue',
            new_name='net_income_margin',
        ),
    ]
