# Generated by Django 3.1.6 on 2021-02-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210213_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='operating_expense_over_cogs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='reconciled_cost_of_revenue',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='COGS'),
        ),
    ]
