# Generated by Django 3.1.6 on 2021-02-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210213_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='ebit_margin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
