# Generated by Django 3.1.6 on 2021-02-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_incomestatement_ebit_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomestatement',
            name='ebit_margin',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='gross_profit_margin',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='net_income_margin',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='operating_expense_over_cogs',
        ),
    ]
