# Generated by Django 3.1.6 on 2021-02-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20210213_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateField(blank=True, null=True)),
                ('beginning_cash', models.FloatField(blank=True, default=0, null=True)),
                ('ending_cash', models.FloatField(blank=True, default=0, null=True)),
                ('free_cash_flow', models.FloatField(blank=True, default=0, null=True)),
                ('investing_cash_flow', models.FloatField(blank=True, default=0, null=True)),
                ('net_income', models.FloatField(blank=True, default=0, null=True)),
                ('operating_cash_flow', models.FloatField(blank=True, default=0, null=True)),
                ('da', models.FloatField(blank=True, default=0, null=True, verbose_name='Depreciation and Amortization')),
                ('capex', models.FloatField(blank=True, default=0, null=True)),
                ('dividend_paid', models.FloatField(blank=True, default=0, null=True)),
                ('from_continuing_financing_activity', models.FloatField(blank=True, default=0, null=True)),
                ('change_in_inventory', models.FloatField(blank=True, default=0, null=True)),
                ('change_in_accountable_payable', models.FloatField(blank=True, default=0, null=True)),
                ('change_in_working_capital', models.FloatField(blank=True, default=0, null=True)),
                ('change_in_accountable_receivable', models.FloatField(blank=True, default=0, null=True)),
                ('common_stock_issurance', models.FloatField(blank=True, default=0, null=True)),
                ('purchase_of_business', models.FloatField(blank=True, default=0, null=True)),
                ('purchase_of_investment', models.FloatField(blank=True, default=0, null=True)),
                ('repayment_of_debt', models.FloatField(blank=True, default=0, null=True)),
                ('repurchase_of_common_stock', models.FloatField(blank=True, default=0, null=True)),
                ('sale_of_investment', models.FloatField(blank=True, default=0, null=True)),
                ('stock_based_compensation', models.FloatField(blank=True, default=0, null=True)),
                ('net_other_financing_charges', models.FloatField(blank=True, default=0, null=True)),
                ('net_other_investing_changes', models.FloatField(blank=True, default=0, null=True)),
                ('change_in_cash_supplemental_as_reported', models.FloatField(blank=True, default=0, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashes', to='stock.mystock')),
            ],
        ),
    ]
