# Generated by Django 3.1.6 on 2021-02-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20210214_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='common_stock_issurance',
            new_name='common_stock_issuance',
        ),
    ]
