# Generated by Django 3.1.6 on 2021-02-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_valuationratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='basic_eps',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
