# Generated by Django 3.1.6 on 2021-02-15 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_incomestatement_basic_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateField(blank=True, null=True)),
                ('ap', models.FloatField(blank=True, default=0, null=True, verbose_name='Account Payable')),
                ('ac', models.FloatField(blank=True, default=0, null=True, verbose_name='Account Receivable')),
                ('cash_and_cash_equivalent', models.FloatField(blank=True, default=0, null=True)),
                ('cash_cash_equivalents_and_short_term_investments', models.FloatField(blank=True, default=0, null=True)),
                ('cash_equivalents', models.FloatField(blank=True, default=0, null=True)),
                ('cash_financial', models.FloatField(blank=True, default=0, null=True)),
                ('commercial_paper', models.FloatField(blank=True, default=0, null=True)),
                ('common_stock_equity', models.FloatField(blank=True, default=0, null=True)),
                ('current_assets', models.FloatField(blank=True, default=0, null=True)),
                ('current_debt', models.FloatField(blank=True, default=0, null=True)),
                ('current_deferred_liabilities', models.FloatField(blank=True, default=0, null=True)),
                ('current_deferred_revenue', models.FloatField(blank=True, default=0, null=True)),
                ('current_liabilities', models.FloatField(blank=True, default=0, null=True)),
                ('gross_ppe', models.FloatField(blank=True, default=0, null=True)),
                ('inventory', models.FloatField(blank=True, default=0, null=True)),
                ('invested_capital', models.FloatField(blank=True, default=0, null=True)),
                ('investmentin_financial_assets', models.FloatField(blank=True, default=0, null=True)),
                ('investments_and_advances', models.FloatField(blank=True, default=0, null=True)),
                ('land_and_improvements', models.FloatField(blank=True, default=0, null=True)),
                ('leases', models.FloatField(blank=True, default=0, null=True)),
                ('long_term_debt', models.FloatField(blank=True, default=0, null=True)),
                ('long_term_debt_and_capital_lease_obligation', models.FloatField(blank=True, default=0, null=True)),
                ('machinery_furniture_equipment', models.FloatField(blank=True, default=0, null=True)),
                ('net_debt', models.FloatField(blank=True, default=0, null=True)),
                ('net_ppe', models.FloatField(blank=True, default=0, null=True)),
                ('net_tangible_assets', models.FloatField(blank=True, default=0, null=True)),
                ('other_current_assets', models.FloatField(blank=True, default=0, null=True)),
                ('other_current_borrowings', models.FloatField(blank=True, default=0, null=True)),
                ('other_current_liabilities', models.FloatField(blank=True, default=0, null=True)),
                ('other_receivables', models.FloatField(blank=True, default=0, null=True)),
                ('other_short_term_investments', models.FloatField(blank=True, default=0, null=True)),
                ('payables', models.FloatField(blank=True, default=0, null=True)),
                ('payables_and_accrued_expenses', models.FloatField(blank=True, default=0, null=True)),
                ('receivables', models.FloatField(blank=True, default=0, null=True)),
                ('retained_earnings', models.FloatField(blank=True, default=0, null=True)),
                ('stockholders_equity', models.FloatField(blank=True, default=0, null=True)),
                ('tangible_book_value', models.FloatField(blank=True, default=0, null=True)),
                ('total_assets', models.FloatField(blank=True, default=0, null=True)),
                ('total_capitalization', models.FloatField(blank=True, default=0, null=True)),
                ('total_debt', models.FloatField(blank=True, default=0, null=True)),
                ('total_non_current_assets', models.FloatField(blank=True, default=0, null=True)),
                ('working_capital', models.FloatField(blank=True, default=0, null=True)),
                ('available_for_sale_securities', models.FloatField(blank=True, default=0, null=True)),
                ('total_tax_payable', models.FloatField(blank=True, default=0, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='stock.mystock')),
            ],
        ),
    ]
