# Generated by Django 3.1.6 on 2021-02-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_balancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='common_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
