# Generated by Django 3.1.6 on 2021-02-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_balancesheet_common_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystock',
            name='beta',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='mystock',
            name='roe',
            field=models.FloatField(default=0, null=True, verbose_name='Return on Equity'),
        ),
        migrations.AddField(
            model_name='mystock',
            name='roi',
            field=models.FloatField(default=0, null=True, verbose_name='Return on Assets'),
        ),
    ]
