# Generated by Django 3.1.6 on 2021-02-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20210215_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystock',
            name='top_ten_institution_ownership',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='mystock',
            name='beta',
            field=models.FloatField(default=5, null=True),
        ),
    ]
