# Generated by Django 3.1.6 on 2021-02-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20210215_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='tax_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
