# Generated by Django 3.1.6 on 2021-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_incomestatement_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystock',
            name='profit_margin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mystock',
            name='shares_outstanding',
            field=models.FloatField(default=0, null=True),
        ),
    ]
