# Generated by Django 3.1.6 on 2021-02-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_auto_20210216_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='ac',
            new_name='ar',
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='total_revenue',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sales'),
        ),
        migrations.AlterField(
            model_name='mystrategyvalue',
            name='method',
            field=models.IntegerField(choices=[(1, 'daily return'), (2, 'overnight return'), (3, 'night day consistency'), (4, 'two daily trend'), (5, 'night day compounded return')], default=1),
        ),
    ]
