# Generated by Django 3.1.7 on 2021-03-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_auto_20210307_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystock',
            name='symbol',
            field=models.CharField(max_length=32),
        ),
    ]
