# Generated by Django 3.1.7 on 2021-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_auto_20210310_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysector',
            name='stocks',
            field=models.ManyToManyField(related_name='sectors', to='stock.MyStock'),
        ),
    ]
