# Generated by Django 3.1.7 on 2021-03-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_auto_20210319_1300'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('stock', 'on')},
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('stock', 'on')},
        ),
        migrations.AlterUniqueTogether(
            name='incomestatement',
            unique_together={('stock', 'on')},
        ),
        migrations.AlterUniqueTogether(
            name='valuationratio',
            unique_together={('stock', 'on')},
        ),
    ]
