# Generated by Django 3.1.7 on 2021-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_auto_20210319_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysector',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mystock',
            name='symbol',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
