# Generated by Django 3.1.7 on 2021-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_auto_20210422_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyStrategyValue',
        ),
    ]
