# Generated by Django 3.1.7 on 2021-05-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_mystock_institution_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='stock.mystock')),
            ],
        ),
    ]
