# Generated by Django 3.1.7 on 2021-05-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_mydiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydiary',
            name='judgement',
            field=models.IntegerField(choices=[(1, 'bull'), (2, 'bear')], default=1),
        ),
        migrations.AddField(
            model_name='mydiary',
            name='was_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mydiary',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='stock.mystock'),
        ),
    ]
