# Generated by Django 3.1.7 on 2021-05-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_auto_20210513_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydiary',
            name='was_correct',
        ),
    ]
