# Generated by Django 3.2.3 on 2021-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_remove_mydiary_was_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('topic', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('link', models.URLField()),
                ('pub_time', models.DateTimeField()),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['-pub_time'],
                'unique_together': {('source', 'topic', 'link')},
                'index_together': {('source', 'topic', 'title')},
            },
        ),
    ]
