# Generated by Django 3.2.8 on 2021-10-08 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0037_mynews'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysector',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='auth.user'),
            preserve_default=False,
        ),
    ]
