# Generated by Django 3.2.8 on 2021-10-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_alter_mysector_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mystock',
            options={},
        ),
        migrations.AlterModelManagers(
            name='mystock',
            managers=[
            ],
        ),
    ]
