# Generated by Django 5.1.15 on 2026-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_mytask_result'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mynews',
            new_name='stock_mynew_source_cce318_idx',
            old_fields=('source', 'topic', 'title'),
        ),
        migrations.RenameIndex(
            model_name='mystockhistorical',
            new_name='stock_mysto_stock_i_51c841_idx',
            old_fields=('stock', 'on'),
        ),
        migrations.AddField(
            model_name='mystock',
            name='d_last_better',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystock',
            name='d_last_lower',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystock',
            name='d_pb',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystock',
            name='d_pe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystock',
            name='d_price_to_cash_premium',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystock',
            name='d_ps',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystockhistorical',
            name='d_gain_probability',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystockhistorical',
            name='d_last_better',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystockhistorical',
            name='d_last_lower',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystockhistorical',
            name='d_next_better',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mystockhistorical',
            name='d_vol_over_share_outstanding',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mystock',
            name='symbol',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
