# Generated by Django 5.1.15 on 2026-06-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_denormalize_computed_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='balancesheet',
            index=models.Index(fields=['stock', 'on'], name='stock_balan_stock_i_226820_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['stock', 'on'], name='stock_cashf_stock_i_c7cff4_idx'),
        ),
        migrations.AddIndex(
            model_name='incomestatement',
            index=models.Index(fields=['stock', 'on'], name='stock_incom_stock_i_054055_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationratio',
            index=models.Index(fields=['stock', 'on'], name='stock_valua_stock_i_d3c257_idx'),
        ),
    ]
