# Generated by Django 5.1.15 on 2026-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_add_indexes_to_statements'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(max_length=32, unique=True)),
                ('data', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
