# Generated by Django 5.1.15 on 2026-06-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_add_ranking_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_on', models.DateField()),
                ('trade_date', models.DateField()),
                ('insider_name', models.CharField(max_length=256)),
                ('insider_title', models.CharField(default='', max_length=128)),
                ('insider_cik', models.CharField(default='', max_length=20)),
                ('transaction_type', models.CharField(max_length=4)),
                ('shares', models.FloatField()),
                ('price_per_share', models.FloatField(null=True)),
                ('total_value', models.FloatField(null=True)),
                ('shares_owned_after', models.FloatField(null=True)),
                ('is_direct', models.BooleanField(default=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insider_trades', to='stock.mystock')),
            ],
            options={
                'ordering': ['-trade_date'],
                'indexes': [models.Index(fields=['stock', '-trade_date'], name='stock_insid_stock_i_2b1825_idx'), models.Index(fields=['stock', 'transaction_type'], name='stock_insid_stock_i_593f5c_idx')],
                'unique_together': {('stock', 'trade_date', 'insider_cik', 'transaction_type', 'shares')},
            },
        ),
    ]
