# Generated by Django 5.1.15 on 2026-06-21 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_insider_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('frequency', models.CharField(default='', max_length=16)),
                ('units', models.CharField(default='', max_length=128)),
                ('category', models.CharField(default='misc', max_length=64)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['category', 'series_id'],
            },
        ),
        migrations.CreateModel(
            name='MacroDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='stock.macroseries')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['series', '-date'], name='stock_macro_series__de8d23_idx')],
                'unique_together': {('series', 'date')},
            },
        ),
    ]
