# Generated by Django 5.1.15 on 2026-06-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_macro_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('fiscal_date_ending', models.DateField(null=True)),
                ('report_time', models.CharField(blank=True, max_length=16, null=True)),
                ('estimated_eps', models.FloatField(null=True)),
                ('reported_eps', models.FloatField(null=True)),
                ('surprise', models.FloatField(null=True)),
                ('surprise_pct', models.FloatField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_events', to='stock.mystock')),
            ],
            options={
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['stock', '-report_date'], name='stock_earni_stock_i_14930a_idx'), models.Index(fields=['report_date'], name='stock_earni_report__08318e_idx')],
                'unique_together': {('stock', 'report_date')},
            },
        ),
    ]
