# Generated by Django 5.1.15 on 2026-06-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_earnings_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('institution_name', models.CharField(max_length=256)),
                ('institution_cik', models.CharField(max_length=20)),
                ('shares', models.BigIntegerField()),
                ('value', models.FloatField()),
                ('change_shares', models.BigIntegerField(null=True)),
                ('change_type', models.CharField(max_length=10, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings_13f', to='stock.mystock')),
            ],
            options={
                'ordering': ['-report_date', '-value'],
                'indexes': [models.Index(fields=['stock', '-report_date'], name='stock_insti_stock_i_e00023_idx')],
                'unique_together': {('stock', 'report_date', 'institution_cik')},
            },
        ),
    ]
