# Generated by Django 5.1.15 on 2026-06-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0050_institutional_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystock',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
