# Generated by Django 5.1.15 on 2026-06-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_stock_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsPriceImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_before', models.FloatField()),
                ('price_after_1d', models.FloatField()),
                ('price_after_5d', models.FloatField(null=True)),
                ('gap_pct', models.FloatField()),
                ('reaction_1d_pct', models.FloatField()),
                ('reaction_5d_pct', models.FloatField(null=True)),
                ('volume_ratio', models.FloatField(null=True)),
                ('earnings_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_impact', to='stock.earningsevent')),
            ],
            options={
                'ordering': ['-earnings_event__report_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMacroCorrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_days', models.IntegerField()),
                ('correlation', models.FloatField()),
                ('computed_at', models.DateField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.macroseries')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_correlations', to='stock.mystock')),
            ],
            options={
                'unique_together': {('stock', 'series', 'window_days')},
            },
        ),
    ]
