# Generated by Django 5.2.16 on 2026-08-07 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0059_dividend_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('behavioral', 'Behavioral / Time-Arbitrage'), ('analytical', 'Analytical'), ('informational', 'Informational')], default='behavioral', help_text='What type of edge do you have?', max_length=32)),
                ('variant_perception', models.TextField(blank=True, default='', help_text='One-liner: what does the market not understand?')),
                ('driver_1', models.CharField(blank=True, default='', help_text="Primary driver (e.g., 'Azure growth rate')", max_length=256)),
                ('driver_2', models.CharField(blank=True, default='', help_text="Secondary driver (e.g., 'Copilot seat count')", max_length=256)),
                ('driver_3', models.CharField(blank=True, default='', help_text="Tertiary driver (e.g., 'CapEx ROI timeline')", max_length=256)),
                ('implied_growth_rate', models.FloatField(blank=True, help_text='Implied growth rate from reverse DCF (decimal, e.g., 0.13 = 13%)', null=True)),
                ('growth_assessment', models.CharField(choices=[('too_high', 'Too High (market too optimistic)'), ('about_right', 'About Right'), ('too_low', 'Too Low (market too pessimistic)')], default='about_right', help_text="Is the market's implied growth reasonable?", max_length=32)),
                ('rerate_mechanism', models.TextField(blank=True, default='', help_text='WHY the market will converge to your view')),
                ('rerate_timeframe', models.CharField(blank=True, default='', help_text="WHEN — e.g., 'Q4 2026 earnings' or '6-12 months'", max_length=64)),
                ('reflexivity_risk', models.CharField(choices=[('low', "Low (price doesn't affect business)"), ('medium', 'Medium'), ('high', 'High (price drop can hurt fundamentals)')], default='low', help_text='Does the stock price path alter the fundamentals?', max_length=16)),
                ('bull_price', models.FloatField(blank=True, null=True)),
                ('bull_probability', models.FloatField(blank=True, help_text='Probability 0-100', null=True)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('base_probability', models.FloatField(blank=True, help_text='Probability 0-100', null=True)),
                ('bear_price', models.FloatField(blank=True, null=True)),
                ('bear_probability', models.FloatField(blank=True, help_text='Probability 0-100', null=True)),
                ('kill_criterion_1', models.CharField(blank=True, default='', help_text="Primary sell trigger (e.g., 'Azure <25% two quarters')", max_length=256)),
                ('kill_criterion_2', models.CharField(blank=True, default='', help_text='Secondary sell trigger', max_length=256)),
                ('kill_criterion_3', models.CharField(blank=True, default='', help_text='Tertiary sell trigger', max_length=256)),
                ('stop_loss_price', models.FloatField(blank=True, help_text='Hard stop-loss price', null=True)),
                ('capital_cycle_phase', models.CharField(blank=True, choices=[('peak', 'Peak Returns / Max Investment'), ('falling', 'Falling Returns / Investment Slowing'), ('trough', 'Trough Returns / Min Investment'), ('rising', 'Rising Returns / Investment Resuming'), ('', 'Not Applicable')], default='', help_text='Where is this industry in the capital cycle?', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active Position'), ('watchlist', 'Watchlist'), ('avoid', 'Avoid')], default='active', max_length=16)),
                ('last_reviewed', models.DateField(auto_now=True, help_text='Auto-updated on save — tracks thesis freshness')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Free-form additional context')),
            ],
            options={
                'verbose_name_plural': 'stock theses',
                'ordering': ['-last_reviewed'],
            },
        ),
        migrations.RenameIndex(
            model_name='dividendevent',
            new_name='stock_divid_stock_i_af7fac_idx',
            old_name='stock_divid_stock_i_idx',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('rsi_below', 'RSI Below Threshold'), ('price_below', 'Price Below Target'), ('price_above', 'Price Above Target'), ('insider_buy', 'Insider Cluster Buy'), ('earnings_soon', 'Earnings Within N Days'), ('drop_days', 'Drop Exceeds N Days'), ('universal_rsi', 'RSI Below (Any Stock)'), ('universal_drop', 'Drop Exceeds N Days (Any Stock)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dividendevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='stockthesis',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='stock.mystock'),
        ),
        migrations.AddField(
            model_name='stockthesis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
