# Generated by Django 5.2.16 on 2026-08-07 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_create_stock_thesis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsCallNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(help_text="e.g., 'Q4 2026'", max_length=8)),
                ('call_date', models.DateField(help_text='Date of the earnings call')),
                ('replay_url', models.URLField(blank=True, default='', help_text='Link to earnings call replay or transcript')),
                ('management_tone', models.CharField(choices=[('confident', 'Confident'), ('cautious', 'Cautious'), ('defensive', 'Defensive'), ('neutral', 'Neutral'), ('evasive', 'Evasive')], default='neutral', help_text='Overall tone of management during the call', max_length=16)),
                ('key_quote', models.TextField(blank=True, default='', help_text='Most important quote from the call (verbatim or paraphrased)')),
                ('guidance_direction', models.CharField(choices=[('raised', 'Raised'), ('maintained', 'Maintained'), ('lowered', 'Lowered'), ('withdrawn', 'Withdrawn'), ('none', 'No Guidance Given')], default='maintained', help_text='Did management raise, maintain, or lower guidance?', max_length=16)),
                ('driver_1_update', models.TextField(blank=True, default='', help_text="Update on primary thesis driver (e.g., 'Azure guided 45%, was 40%')")),
                ('driver_2_update', models.TextField(blank=True, default='', help_text='Update on secondary thesis driver')),
                ('driver_3_update', models.TextField(blank=True, default='', help_text='Update on tertiary thesis driver')),
                ('kill_triggered', models.BooleanField(default=False, help_text='Did any kill criterion from the thesis trigger this quarter?')),
                ('kill_notes', models.TextField(blank=True, default='', help_text='If kill triggered, which criterion and why')),
                ('analyst_pushback', models.TextField(blank=True, default='', help_text='What did analysts push back on? (reveals where debate lives)')),
                ('what_management_avoided', models.TextField(blank=True, default='', help_text='What questions did management dodge or give non-answers to?')),
                ('stock_reaction_pct', models.FloatField(blank=True, help_text='Stock price change on earnings day (%)', null=True)),
                ('surprise_vs_consensus', models.TextField(blank=True, default='', help_text='Brief: beat/miss by how much on what metric')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_call_notes', to='stock.mystock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_call_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-call_date'],
                'unique_together': {('stock', 'user', 'quarter')},
            },
        ),
    ]
