# Generated by Django 5.2.16 on 2026-08-07 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0061_create_earnings_call_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('regulatory', 'Regulatory / Legal'), ('competitive', 'Competitive'), ('operational', 'Operational'), ('financial', 'Financial'), ('macro', 'Macro / Economic'), ('technology', 'Technology / Disruption'), ('management', 'Management / Governance')], help_text='Type of risk', max_length=32)),
                ('description', models.TextField(help_text="Specific risk factor (e.g., 'OpenAI may terminate partnership')")),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('existential', 'Existential')], default='medium', help_text='How bad if this materializes?', max_length=16)),
                ('currently_materializing', models.BooleanField(default=False, help_text='Is this risk currently happening / showing early signs?')),
                ('materializing_evidence', models.TextField(blank=True, default='', help_text='What evidence suggests this risk is materializing?')),
                ('source', models.CharField(blank=True, default='10-K', help_text='Where this was identified (10-K, proxy, earnings call, etc.)', max_length=64)),
                ('last_assessed', models.DateField(auto_now=True, help_text='Last time this risk factor was reviewed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='stock.mystock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-currently_materializing', '-severity', 'category'],
            },
        ),
    ]
