symbols:
  # group for US stocks
  US: |
    VOO, SPY, AAPL, SBUX, MSFT, AMZN, BFAM, VMW, ABNB, PYPL, AMD,
    EBAY, TGT, NET, TSM, BBBY, TSLA, SQ, BBY, RCL,PLTR,ROKU,
    SHOP,IQ,CVS, NOK,VNT,BABA, CRM, WOOF, QCOM, KO, ORCL, HD, BURL,
    DOCU, POSH, BCOW, KIRK, PLCE, XPEV, REV, JD, PRTY, CPNG, GOOGL,
    SY, HUIZ, NVDA, ADBE, NFLX, DIS,INTC,MRK,MA,V,
    UNH,PG,FB,BAC,NKE,TXN,HON,COST,TJX,FDX,SHW,BSX,WM,DG,SYY,MAR,XLNX,
    ROK,AZO,ETSY,DLTR,EXPE,CCL,KMX,NTAP,PKI,DPZ,LB,AAP,NCLH, PDD


  # group for china stocks
  china: |
    600000.SS
