FROM python:3
ENV PYTHONUNBUFFERED 1

# Install system packages
RUN apt-get update && apt-get install -y \
    memcached \
    libmemcached-dev

# Upgrade pip
RUN pip install --upgrade pip

# For some strange reason, this is required before
# we hit `pip install -r`
RUN pip install requests

# Set up code destination
RUN mkdir /code
WORKDIR /code

# Install dependencies
ADD requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt
