apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-nginx-conf
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.nginxConf | toYaml | indent 1 }}
