from stock.models import BalanceSheet
from stock.workers.base import StatementWorker


class MyBalanceSheet(StatementWorker):
    model = BalanceSheet
    yahoo_method = "balance_sheet"
    mapping = {
        "ap": "AccountsPayable",
        "cash_and_cash_equivalent": "CashAndCashEquivalents",
        "cash_cash_equivalents_and_short_term_investments": "CashCashEquivalentsAndShortTermInvestments",
        "common_stock": "CommonStock",
        "common_stock_equity": "CommonStockEquity",
        "invested_capital": "InvestedCapital",
        "long_term_debt_and_capital_lease_obligation": "LongTermDebtAndCapitalLeaseObligation",
        "machinery_furniture_equipment": "MachineryFurnitureEquipment",
        "net_ppe": "NetPPE",
        "net_tangible_assets": "NetTangibleAssets",
        "payables": "Payables",
        "payables_and_accrued_expenses": "PayablesAndAccruedExpenses",
        "retained_earnings": "RetainedEarnings",
        "stockholders_equity": "StockholdersEquity",
        "tangible_book_value": "TangibleBookValue",
        "total_assets": "TotalAssets",
        "total_capitalization": "TotalCapitalization",
        "total_debt": "TotalDebt",
        "total_non_current_assets": "TotalNonCurrentAssets",
        "working_capital": "WorkingCapital",
        "gross_ppe": "GrossPPE",
        "current_assets": "CurrentAssets",
        "current_liabilities": "CurrentLiabilities",
        "receivables": "Receivables",
        "other_short_term_investments": "OtherShortTermInvestments",
        "long_term_debt": "LongTermDebt",
        "other_current_liabilities": "OtherCurrentLiabilities",
        "land_and_improvements": "LandAndImprovements",
        "ar": "AccountsReceivable",
        "other_current_assets": "OtherCurrentAssets",
        "investments_and_advances": "InvestmentsAndAdvances",
        "current_debt": "CurrentDebt",
        "inventory": "Inventory",
        "total_tax_payable": "TotalTaxPayable",
        "available_for_sale_securities": "AvailableForSaleSecurities",
        "other_receivables": "OtherReceivables",
        "other_current_borrowings": "OtherCurrentBorrowings",
        "investmentin_financial_assets": "InvestmentinFinancialAssets",
        "cash_equivalents": "CashEquivalents",
        "cash_financial": "CashFinancial",
        "commercial_paper": "CommercialPaper",
        "current_deferred_liabilities": "CurrentDeferredLiabilities",
        "current_deferred_revenue": "CurrentDeferredRevenue",
        "leases": "Leases",
        "net_debt": "NetDebt",
        "accumulated_depreciation": "AccumulatedDepreciation",
        "allowance_for_doubtful_accounts_receivable": "AllowanceForDoubtfulAccountsReceivable",
        "properties": "Properties",
        "goodwill": "Goodwill",
        "goodwill_and_other_intangible_assets": "GoodwillAndOtherIntangibleAssets",
        "other_intangible_assets": "OtherIntangibleAssets",
        "other_non_current_assets": "OtherNonCurrentAssets",
        "current_debt_and_capital_lease_obligation": "CurrentDebtAndCapitalLeaseObligation",
        "total_non_current_liabilities_net_minority_interest": "TotalNonCurrentLiabilitiesNetMinorityInterest",
        "non_current_deferred_liabilities": "NonCurrentDeferredLiabilities",
        "tradeand_other_payables_non_current": "TradeandOtherPayablesNonCurrent",
        "other_non_current_liabilities": "OtherNonCurrentLiabilities",
        "non_current_deferred_taxes_liabilities": "NonCurrentDeferredTaxesLiabilities",
        "non_current_deferred_revenue": "NonCurrentDeferredRevenue",
        "share_issued": "ShareIssued",
    }
